# Generated by Django 3.2.7 on 2021-09-23 08:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_activation_key_expires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuserprofile',
            old_name='aboutMe',
            new_name='aboutme',
        ),
        migrations.RenameField(
            model_name='shopuserprofile',
            old_name='tagLine',
            new_name='tagline',
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 8, 48, 7, 490657, tzinfo=utc)),
        ),
    ]
